version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.8"
  jobs:
    post_install:
      - git clone https://github.com/lh3/bwa.git
      - pip install poetry==1.8.3
      - poetry config virtualenvs.create false
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install
sphinx:
  configuration: docs/conf.py
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs