version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.9"
  jobs:
    pre_install:
      - pip install poetry==2.1.1
      - poetry config virtualenvs.create false
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install
  apt_packages:
    - libbz2-dev
    - libcurl4-openssl-dev
    - liblzma-dev
    - libssl-dev
    - libdeflate-dev
submodules:
  include: all
  recursive: true
sphinx:
  configuration: docs/conf.py
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
