name: Build wheels
author: Nils Homer (@nh13)
description: 'Builds wheels using cibuildwheel'

branding:
  icon: "code"
  color: "green"

runs:
  using: "composite"
  steps:
    - name: Build wheels
      uses: pypa/cibuildwheel@8d2b08b68458a16aeb24b64e68a09ab1c8e82084 # v3.4.1
      with:
        package-dir: .
        output-dir: wheelhouse
        config-file: "{package}/pyproject.toml"
