name: Build wheels
author: Nils Homer (@nh13)
description: 'Builds wheels using cibuildwheel'

branding:
  icon: "code"
  color: "green"

runs:
  using: "composite"
  steps:
    - name: Build wheels
      uses: pypa/cibuildwheel@v3.3.0
      with:
        package-dir: .
        output-dir: wheelhouse
        config-file: "{package}/pyproject.toml"
